export const CONSTANTS = {
  ADD_CARD: "ADD_CARD",
  REMOVE_CARD: "REMOVE_CARD",
  DRAG_HAPPENED: "DRAG_HAPPENED",
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  START_WORKOUT: "START_WORKOUT",
  REDIRECT: "REDIRECT",
  UPDATE_STATE: "UPDATE_STATE",
};
